# 🐼 **Pandas Practice 2**

---

# ⚙️ **0. Setup**

### _Run this cell first — it loads the dataset used throughout the notebook._

---

In [2]:
import pandas as pd
import numpy as np

url = "/Users/shubhamsingh/Desktop/ML/Titanic-Dataset.csv"
df = pd.read_csv(url)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# 🏗️ **1. Creating DataFrames from Dict & Column Data Types**

### _`pd.DataFrame(dict)` → build a DataFrame from a dictionary of lists | `.dtypes` → check each column's data type | `.astype()` → convert a column's data type_

---

#### **Q1.1 Create a DataFrame called `students` from a dictionary with columns `name` (5 student names), `age` (integers), and `marks` (floats). Print the DataFrame and check the dtype of every column using `.dtypes`.**

---

In [6]:
# Write your code here
students = pd.DataFrame({
    "name": ["Rahul", "Amit", "Priya", "Sneha", "Rohan"],"age": [20, 21, 19, 22, 20],"marks": [85.5, 90, 78.5, 88, 92]
})

print(students)
print(students.dtypes)

    name  age  marks
0  Rahul   20   85.5
1   Amit   21   90.0
2  Priya   19   78.5
3  Sneha   22   88.0
4  Rohan   20   92.0
name         str
age        int64
marks    float64
dtype: object

#### **Q1.2 In `students`, convert the `age` column to `float` and the `marks` column to `int` using `.astype()`. Print `.dtypes` again to confirm the change.**

---

In [4]:
# Write your code here
students["age"] = students["age"].astype(float)
students["marks"] = students["marks"].astype(int)

print(students.dtypes)

name         str
age      float64
marks      int64
dtype: object

# 🧵 **2. Standalone Series, Custom Indexing & .values**

### _`pd.Series(data)` → create a standalone Series | `pd.Series(data, index=[...])` → give it custom index labels | `.values` → get the underlying data as a plain NumPy array_

---

#### **Q2.1 Create a standalone Series called `city_temp` holding the temperature of 5 cities of your choice, using the city names as a custom index, e.g. `index=['Delhi','Mumbai',...]`.**

---

In [7]:
# Write your code here
city_temp=pd.Series([32,30,28,35,27],index=['Delhi','Mumbai','Pune','Chennai','Bangalore'])
print(city_temp)

Delhi        32
Mumbai       30
Pune         28
Chennai      35
Bangalore    27
dtype: int64

#### **Q2.2 From `city_temp`, print the value for one city using its label (e.g. `city_temp['Delhi']`), then print the entire Series as a NumPy array using `.values`.**

---

In [8]:
# Write your code here
print(city_temp["Delhi"])
print(city_temp.values)

32
[32 30 28 35 27]

# 👀 **3. .sample() for Data Preview**

### _`.sample(n)` → randomly select n rows | `.sample(frac=x)` → randomly select a fraction of the rows | gives an unbiased preview, unlike `.head()` which always shows the same rows_

---

#### **Q3.1 Use `.sample(5)` on `df` to view 5 random passengers. Run the cell a couple of times and confirm the rows change each time.**

---

In [9]:
# Write your code here
print(df.sample(5))

     PassengerId  Survived  Pclass                                      Name  \
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
50            51         0       3                Panula, Master. Juha Niilo
840          841         0       3               Alhomaki, Mr. Ilmari Rudolf
876          877         0       3             Gustafsson, Mr. Alfred Ossian
688          689         0       3           Fischer, Mr. Eberhard Thelander

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S
50     male   7.0      4      1           3101295  39.6875   NaN        S
840    male  20.0      0      0  SOTON/O2 3101287   7.9250   NaN        S
876    male  20.0      0      0              7534   9.8458   NaN        S
688    male  18.0      0      0            350036   7.7958   NaN        S

#### **Q3.2 Use `.sample(frac=0.1, random_state=1)` to select 10% of the rows from `df`, and print how many rows were selected.**

---

In [12]:
# Write your code here
sample_df = df.sample(frac=0.1, random_state=1)
sample_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
223,224,0,3,"Nenkoff, Mr. Christo",male,NaN,0,0,349234,7.8958,NaN,S
84,85,1,2,"Ilett, Miss. Bertha",female,17.0,0,0,SO/C 14885,10.5000,NaN,S
680,681,0,3,"Peters, Miss. Katie",female,NaN,0,0,330935,8.1375,NaN,Q
535,536,1,2,"Hart, Miss. Eva Miriam",female,7.0,0,2,F.C.C. 13529,26.2500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
473,474,1,2,"Jerwan, Mrs. Amin S (Marie Marthe Thuillard)",female,23.0,0,0,SC/AH Basle 541,13.7917,D,C
713,714,0,3,"Larsson, Mr. August Viktor",male,29.0,0,0,7545,9.4833,NaN,S
589,590,0,3,"Murdlin, Mr. Joseph",male,NaN,0,0,A./5. 3235,8.0500,NaN,S
598,599,0,3,"Boulos, Mr. Hanna",male,NaN,0,0,2664,7.2250,NaN,C
813,814,0,3,"Andersson, Miss. Ebba Iris Alfrida",female,6.0,4,2,347082,31.2750,NaN,S

# 🎯 **4. Conditional Column Assignment**

### _`df.loc[condition, 'col'] = value` → assign a value only to rows that meet a condition | `np.where(condition, a, b)` → vectorized if-else, faster than `.apply()` with a lambda_

---

#### **Q4.1 Using `.loc[]`, create a new column `fare_level` and set it to `'High'` where `Fare > 30` and `'Low'` everywhere else — do this with two separate `.loc[]` assignment lines.**

---

In [17]:
# Write your code here
df.loc[df["Fare"] > 30, "fare_level"] = "High"
df.loc[df["Fare"] <= 30, "fare_level"] = "Low"
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_level,fare_level_v2
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Low,Low
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,High,High
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Low,Low
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,High,High
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Low,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Low,Low
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Low,Low
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Low,Low
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Low,Low
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Low,Low

#### **Q4.2 Recreate the same idea as a new column `fare_level_v2`, but this time in a single line using `np.where()` instead of `.loc[]`.**

---

In [18]:
# Write your code here
df["fare_level_v2"] = np.where(df["Fare"] > 30, "High", "Low")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_level,fare_level_v2
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Low,Low
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,High,High
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Low,Low
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,High,High
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Low,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Low,Low
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Low,Low
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Low,Low
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Low,Low
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Low,Low

# 🔎 **5. Multi-Condition Queries on the Dataset**

### _Combine multiple conditions with `&`, `|`, `~` to answer specific questions about the data._

---

#### **Q5.1 Filter `df` for female passengers (`Sex == 'female'`) who survived (`Survived == 1`) and were traveling in 1st class (`Pclass == 1`). How many such passengers are there?**

---

In [23]:
# Write your code here
result = df[(df["Sex"] == "female") & (df["Survived"] == 1) & (df["Pclass"] == 1)]
result

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_level,fare_level_v2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,High,High
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,High,High
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,Low,Low
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C,High,High
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C,High,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S,High,High
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S,Low,Low
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,High,High
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,High,High
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Low,Low

#### **Q5.2 Filter `df` for passengers who are NOT in 3rd class using `~`, and whose `Age` is missing (`.isnull()`).**

---

In [24]:
# Write your code here
result = df[(~(df["Pclass"] == 3)) & (df["Age"].isnull())]
result

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_level,fare_level_v2
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S,Low,Low
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C,High,High
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S,High,High
64,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C,Low,Low
166,167,1,1,"Chibnall, Mrs. (Edith Martha Bowerman)",female,NaN,0,1,113505,55.0000,E33,S,High,High
168,169,0,1,"Baumann, Mr. John D",male,NaN,0,0,PC 17318,25.9250,NaN,S,Low,Low
181,182,0,2,"Pernot, Mr. Rene",male,NaN,0,0,SC/PARIS 2131,15.0500,NaN,C,Low,Low
185,186,0,1,"Rood, Mr. Hugh Roscoe",male,NaN,0,0,113767,50.0000,A32,S,High,High
256,257,1,1,"Thorne, Mrs. Gertrude Maybelle",female,NaN,0,0,PC 17585,79.2000,NaN,C,High,High
270,271,0,1,"Cairns, Mr. Alexander",male,NaN,0,0,113798,31.0000,NaN,S,High,High
277,278,0,2,"Parkes, Mr. Francis ""Frank""",male,NaN,0,0,239853,0.0000,NaN,S,Low,Low
284,285,0,1,"Smith, Mr. Richard William",male,NaN,0,0,113056,26.0000,A19,S,Low,Low
295,296,0,1,"Lewy, Mr. Ervin G",male,NaN,0,0,PC 17612,27.7208,NaN,C,Low,Low
298,299,1,1,"Saalfeld, Mr. Adolphe",male,NaN,0,0,19988,30.5000,C106,S,High,High
303,304,1,2,"Keane, Miss. Nora A",female,NaN,0,0,226593,12.3500,E101,Q,Low,Low
306,307,1,1,"Fleming, Miss. Margaret",female,NaN,0,0,17421,110.8833,NaN,C,High,High
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S,High,High
351,352,0,1,"Williams-Lambert, Mr. Fletcher Fellows",male,NaN,0,0,113510,35.0000,C128,S,High,High
375,376,1,1,"Meyer, Mrs. Edgar Joseph (Leila Saks)",female,NaN,1,0,PC 17604,82.1708,NaN,C,High,High
413,414,0,2,"Cunningham, Mr. Alfred Fleming",male,NaN,0,0,239853,0.0000,NaN,S,Low,Low
457,458,1,1,"Kenyon, Mrs. Frederick R (Marion)",female,NaN,1,0,17464,51.8625,D21,S,High,High
466,467,0,2,"Campbell, Mr. William",male,NaN,0,0,239853,0.0000,NaN,S,Low,Low
475,476,0,1,"Clifford, Mr. George Quincy",male,NaN,0,0,110465,52.0000,A14,S,High,High
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0000,NaN,S,Low,Low
507,508,1,1,"Bradley, Mr. George (""George Arthur Brayton"")",male,NaN,0,0,111427,26.5500,NaN,S,Low,Low
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S,High,High
547,548,1,2,"Padro y Manent, Mr. Julian",male,NaN,0,0,SC/PARIS 2146,13.8625,NaN,C,Low,Low
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C,High,High
596,597,1,2,"Leitch, Miss. Jessie Wills",female,NaN,0,0,248727,33.0000,NaN,S,High,High
602,603,0,1,"Harrington, Mr. Charles H",male,NaN,0,0,113796,42.4000,NaN,S,High,High
633,634,0,1,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0000,NaN,S,Low,Low
669,670,1,1,"Taylor, Mrs. Elmer Zebley (Juliet Cummins Wright)",female,NaN,1,0,19996,52.0000,C126,S,High,High
674,675,0,2,"Watson, Mr. Ennis Hastings",male,NaN,0,0,239856,0.0000,NaN,S,Low,Low
711,712,0,1,"Klaber, Mr. Herman",male,NaN,0,0,113028,26.5500,C124,S,Low,Low
732,733,0,2,"Knight, Mr. Robert J",male,NaN,0,0,239855,0.0000,NaN,S,Low,Low
740,741,1,1,"Hawksford, Mr. Walter James",male,NaN,0,0,16988,30.0000,D45,S,Low,Low
766,767,0,1,"Brewe, Dr. Arthur Jackson",male,NaN,0,0,112379,39.6000,NaN,C,High,High
793,794,0,1,"Hoyt, Mr. William Fisher",male,NaN,0,0,PC 17600,30.6958,NaN,C,High,High
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0000,B102,S,Low,Low
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C,Low,Low
849,850,1,1,"Goldenberg, Mrs. Samuel L (Edwiga Grabowska)",female,NaN,1,0,17453,89.1042,C92,C,High,High

# 🧽 **6. Removing Missing Values with .dropna()**

### _`.dropna()` → drop rows with any missing value | `.dropna(subset=[...])` → drop rows only when specific columns are missing | `.dropna(axis=1)` → drop columns instead of rows_

---

#### **Q6.1 Check how many rows in `df` have a missing `Age`, then create `df_clean` by dropping only those rows using `.dropna(subset=['Age'])`.**

---

In [29]:
# Write your code here
print(df["Age"].isnull().sum())
df_clean = df.dropna(subset=["Age"])
print(df_clean.shape)

177
(714, 14)

#### **Q6.2 Compare the `.shape` of `df` before and after plain `.dropna()` (which drops a row if ANY column has a missing value). What is the difference, and why?**

---

In [32]:
# Write your code here
print(df.shape)
print(df_dropna.shape)

(891, 14)
(183, 14)

# 🧮 **7. GroupBy: First/Last Values & size() vs count()**

### _`.first()` / `.last()` → first/last row's value in each group | `.size()` → number of rows per group (includes NaNs) | `.count()` → number of non-null values per group, per column_

---

#### **Q7.1 Group `df` by `Pclass` and use `.first()` and `.last()` to see the first and last passenger listed for each class.**

---

In [34]:
# Write your code here
print(df.groupby("Pclass").first())
print(df.groupby("Pclass").last())

        PassengerId  Survived  \
Pclass
1                 2         1
2                10         1
3                 1         0

                                                     Name     Sex   Age  \
Pclass
1       Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                     Nasser, Mrs. Nicholas (Adele Achem)  female  14.0
3                                 Braund, Mr. Owen Harris    male  22.0

        SibSp  Parch     Ticket     Fare Cabin Embarked fare_level  \
Pclass
1           1      0   PC 17599  71.2833   C85        C       High
2           1      0     237736  30.0708   D56        C       High
3           1      0  A/5 21171   7.2500    G6        S        Low

       fare_level_v2
Pclass
1               High
2               High
3                Low
        PassengerId  Survived                   Name   Sex   Age  SibSp  \
Pclass
1               890         1  Behr, Mr. Karl Howell  male  26.0      0
2               887         0  Montvila, Rev. Juozas  male  27.0      0
3               891         0    Dooley, Mr. Patrick  male  32.0      0

        Parch  Ticket   Fare Cabin Embarked fare_level fare_level_v2
Pclass
1           0  111369  30.00  C148        C        Low           Low
2           0  211536  13.00   E77        S        Low           Low
3           0  370376   7.75  E121        Q        Low           Low

#### **Q7.2 Group `df` by `Embarked` and compare `.size()` vs `.count()`. Are the numbers the same for every column? Why might they differ for a column like `Age`?**

---

In [35]:
# Write your code here
print(df.groupby("Embarked").size())
print(df.groupby("Embarked").count())

Embarked
C    168
Q     77
S    644
dtype: int64
          PassengerId  Survived  Pclass  Name  Sex  Age  SibSp  Parch  Ticket  \
Embarked
C                 168       168     168   168  168  130    168    168     168
Q                  77        77      77    77   77   28     77     77      77
S                 644       644     644   644  644  554    644    644     644

          Fare  Cabin  fare_level  fare_level_v2
Embarked
C          168     69         168            168
Q           77      4          77             77
S          644    129         644            644

#### **Q7.3 Group `df` by `Pclass` and use `.size()` to count passengers per class, then use `.count()` on just the `Age` column to see how many passengers per class have a known age.**

---

In [36]:
# Write your code here
print(df.groupby("Pclass").size())
print(df.groupby("Pclass")["Age"].count())

Pclass
1    216
2    184
3    491
dtype: int64
Pclass
1    186
2    173
3    355
Name: Age, dtype: int64

# 🏷️ **8. Named Aggregations with agg()**

### _`.agg(new_col=('source_col', 'func'))` → give custom, readable names to aggregated columns instead of the default multi-level column names_

---

#### **Q8.1 Group `df` by `Pclass` and use named aggregation to build a summary with columns `avg_fare` (mean of Fare) and `max_age` (max of Age).**

---

In [41]:
# Write your code here
df.groupby("Pclass").agg(avg_fare=("Fare", "mean"),max_age=("Age", "max"))

         avg_fare  max_age
Pclass
1       84.154687     80.0
2       20.662183     70.0
3       13.675550     74.0

#### **Q8.2 Group `df` by `Pclass` and `Sex` together, and use named aggregation to create `avg_age` (mean of Age) and `total_passengers` (count of PassengerId).**

---

In [43]:
# Write your code here
summary=df.groupby(["Pclass", "Sex"]).agg(avg_age=("Age", "mean"),total_passengers=("PassengerId", "count"))
summary

                 avg_age  total_passengers
Pclass Sex
1      female  34.611765                94
       male    41.281386               122
2      female  28.722973                76
       male    30.740707               108
3      female  21.750000               144
       male    26.507589               347

# 🧩 **9. Custom Aggregations with agg()**

### _`.agg()` isn't limited to built-in strings like `'mean'` or `'max'` — you can also pass a `lambda` or your own custom function to compute anything you need per group_

---

#### **Q9.1 Group `df` by `Pclass` and use `.agg()` with a `lambda` function to find the range (`max - min`) of `Fare` for each class.**

---

In [46]:
# Write your code here
range = df.groupby("Pclass")["Fare"].agg(lambda x: x.max() - x.min())
range

Pclass
1    512.3292
2     73.5000
3     69.5500
Name: Fare, dtype: float64

#### **Q9.2 Write your own custom function called `age_range(x)` that returns `x.max() - x.min()`. Group `df` by `Embarked` and pass this function into `.agg()` to find the age range for each embarkation port.**

---

In [53]:
# Write your code here
result = df.groupby("Embarked")["Age"].agg(age_range)
print(result)

NameError: name 'age_range' is not defined

# 📋 **10. Creating a Summary Table (pivot_table)**

### _`pd.pivot_table(df, values=, index=, columns=, aggfunc=)` → reshape data into a spreadsheet-style summary table_

---

#### **Q10.1 Create a pivot table from `df` showing the average `Fare`, with `Pclass` as rows and `Sex` as columns.**

---

In [ ]:
# Write your code here

#### **Q10.2 Create a pivot table from `df` showing the survival rate (mean of `Survived`), with `Pclass` as rows and `Sex` as columns.**

---

In [ ]:
# Write your code here

# 🔍 **11. Filtering Groups**

### _`.groupby('col').filter(func)` → keep only the groups for which a condition on the WHOLE group is True — different from row-wise filtering_

---

#### **Q11.1 Group `df` by `Embarked` and keep only the groups that have more than 100 passengers, using `.groupby().filter()`.**

---

In [51]:
# Write your code here
sample = df.groupby("Embarked").filter(lambda x: len(x) > 100)
print(sample['Embarked'].value_counts())

Embarked
S    644
C    168
Name: count, dtype: int64

#### **Q11.2 Group `df` by `Pclass` and keep only the groups where the average `Fare` is greater than 20.**

---

In [52]:
# Write your code here
sample = df.groupby("Pclass").filter(lambda x: x["Fare"].mean() > 20)
sample

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_level,fare_level_v2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,High,High
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,High,High
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,High,High
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,High,High
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,Low,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,Low,Low
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S,Low,Low
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Low,Low
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Low,Low
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Low,Low

# 🐞 **12. Common Indexing Syntax Errors (Debug It)**

### _These snippets look almost right but throw an error or give a wrong result. Spot the mistake, explain it in a comment, and write the corrected line._

---

#### **Q12.1 This line is meant to select the `Age` and `Fare` columns together but throws an error. Find the bug and fix it: `df['Age', 'Fare']`**

---

In [48]:
# Write your code here
df[["Age", "Fare"]]

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

#### **Q12.2 This line is meant to select rows 2 to 5 using `.iloc` but only returns 3 rows instead of 4. Explain why, and write the version that actually returns 4 rows: `df.iloc[2:5]`**

---

In [49]:
# Write your code here
df.iloc[2:6]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_level,fare_level_v2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Low,Low
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,High,High
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Low,Low
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,Low,Low

# 🔥 **13. Challenge Questions**

### _These combine several techniques from this notebook. Take your time._

---

#### **C1. Using `df`, build a summary table (via `pivot_table` or `groupby` + named `agg()`) showing, for each `Pclass`: average `Fare`, average `Age`, and total number of passengers — sorted from highest to lowest average `Fare`.**

---

In [ ]:
# Write your code here

#### **C2. Drop rows with a missing `Age` from `df`, create a new column `age_group` using conditional assignment (`'Child'` if `Age < 18` else `'Adult'`), then group by `Pclass` and `age_group` to find the survival rate for each combination.**

---

In [ ]:
# Write your code here

#### **C3. Take a random sample of 200 passengers from `df` using `.sample(n=200, random_state=42)`. From this sample, filter passengers who are male and did not survive. Then group this filtered data by `Pclass`, and using named aggregation, create `avg_fare` and `passenger_count`.**

---

In [ ]:
# Write your code here