# 🐼 **Pandas Practice 1**

---

# ⚙️ **0. Setup**

### _Run this cell first — it loads the dataset used throughout the notebook._

---

In [2]:
import pandas as pd
import numpy as np

url = "/Users/shubhamsingh/Desktop/ML/mpg.csv"
df = pd.read_csv(url)
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

# 🔍 **1. Basic Exploration**

### _`.head(n)` / `.tail(n)` → first/last rows | `.shape` → (rows, cols) | `.columns` → column names | `.dtypes` → column data types_

---

**Q1.1 Display the first 7 rows and the last 4 rows of `df`.**

In [3]:
# Write your code here
df.head(7)
print(df.tail(4))

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
394  44.0          4          97.0        52.0    2130          24.6
395  32.0          4         135.0        84.0    2295          11.6
396  28.0          4         120.0        79.0    2625          18.6
397  31.0          4         119.0        82.0    2720          19.4

     model_year  origin           name
394          82  europe      vw pickup
395          82     usa  dodge rampage
396          82     usa    ford ranger
397          82     usa     chevy s-10

**Q1.2 Print the shape of `df`, the list of column names, and the dtype of each column.**

In [4]:
# Write your code here
print(df.shape)
print(df.columns.tolist())
print(df.dtypes)

(398, 9)
['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'name']
mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin              str
name                str
dtype: object

**Q1.3 Use `.info()` and `.describe()` to get a summary of the dataset. What does `.describe()` tell you about the `mpg` column?**

In [5]:
# Write your code here
df.info()
print(df.describe())

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    str
 8   name          398 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 28.1 KB
              mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  392.000000   398.000000
mean    23.514573    5.454774    193.425879  104.469388  2970.424623
std      7.815984    1.701004    104.269838   38.491160   846.841774
min      9.000000    3.000000     68.000000   46.000000  1613.000000
25%     17.500000    4.000000    104.250000   75.000000  2223.750000
50%     23.000000    4.000000    148.500000   93.500000  2803.500000
75%     29.000000    8.000000    262.000000  126.000000  3608.000000
max     46.600000    8.000000    455.000000  230.000000  5140.000000

       acceleration  model_year
count    398.000000  398.000000
mean      15.568090   76.010050
std        2.757689    3.697627
min        8.000000   70.000000
25%       13.825000   73.000000
50%       15.500000   76.000000
75%       17.175000   79.000000
max       24.800000   82.000000

**Q1.4 Unpack `.shape` into two variables (e.g. `rows, cols = df.shape`) and print how many rows and columns the dataset has.**

In [6]:
# Write your code here
rows, cols = df.shape

print(rows)
print(cols)

398
9

# 🎯 **2. Selecting Columns & Rows**

### _`df['col']` → single column (Series) | `df[['a','b']]` → multiple columns (DataFrame) | `.loc[rows, cols]` → label-based | `.iloc[rows, cols]` → position-based_

---

**Q2.1 Select only the `mpg` and `name` columns and store in a new variable.**

In [7]:
# Write your code here
selected = df[['mpg', 'name']]
selected

      mpg                       name
0    18.0  chevrolet chevelle malibu
1    15.0          buick skylark 320
2    18.0         plymouth satellite
3    16.0              amc rebel sst
4    17.0                ford torino
..    ...                        ...
393  27.0            ford mustang gl
394  44.0                  vw pickup
395  32.0              dodge rampage
396  28.0                ford ranger
397  31.0                 chevy s-10

[398 rows x 2 columns]

**Q2.2 Use `.loc` to get rows 5 to 10 (inclusive) showing only the `mpg`, `cylinders`, and `horsepower` columns.**

In [8]:
# Write your code here
df.loc[5:10, ['mpg','cylinders','horsepower']]

     mpg  cylinders  horsepower
5   15.0          8       198.0
6   14.0          8       220.0
7   14.0          8       215.0
8   14.0          8       225.0
9   15.0          8       190.0
10  15.0          8       170.0

**Q2.3 Use `.iloc` to get the first 3 rows and the last 2 columns of `df`.**

In [9]:
# Write your code here
df.iloc[:3, -2:]

  origin                       name
0    usa  chevrolet chevelle malibu
1    usa          buick skylark 320
2    usa         plymouth satellite

**Q2.4 Select the `mpg` column using both `df['mpg']` and `df.mpg`, and confirm that both give the same result.**

In [ ]:
# Write your code here
print(df['mpg'])
print(df.mpg)

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64
0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

NameError: name 'mpg1' is not defined

# 🧮 **3. Filtering / Boolean Indexing**

### _`df[df['col'] > x]` → condition-based filtering | combine conditions with `&` (and) / `|` (or), each wrapped in `()`_

---

**Q3.1 Filter and display all cars with `mpg` greater than 30.**

In [12]:
# Write your code here
df[df['mpg'] > 30]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
53,31.0,4,71.0,65.0,1773,19.0,71,japan,toyota corolla 1200
54,35.0,4,72.0,69.0,1613,18.0,71,japan,datsun 1200
129,31.0,4,79.0,67.0,1950,19.0,74,japan,datsun b210
131,32.0,4,71.0,65.0,1836,21.0,74,japan,toyota corolla 1200
144,31.0,4,76.0,52.0,1649,16.5,74,japan,toyota corona
...,...,...,...,...,...,...,...,...,...
390,32.0,4,144.0,96.0,2665,13.9,82,japan,toyota celica gt
391,36.0,4,135.0,84.0,2370,13.0,82,usa,dodge charger 2.2
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

**Q3.2 Filter all cars from `origin == 'japan'` that also have `horsepower` less than 100.**

In [13]:
# Write your code here
df[(df['origin'] == 'japan') & (df['horsepower'] < 100)]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
14,24.0,4,113.0,95.0,2372,15.0,70,japan,toyota corona mark ii
18,27.0,4,97.0,88.0,2130,14.5,70,japan,datsun pl510
29,27.0,4,97.0,88.0,2130,14.5,71,japan,datsun pl510
31,25.0,4,113.0,95.0,2228,14.0,71,japan,toyota corona
53,31.0,4,71.0,65.0,1773,19.0,71,japan,toyota corolla 1200
...,...,...,...,...,...,...,...,...,...
382,34.0,4,108.0,70.0,2245,16.9,82,japan,toyota corolla
383,38.0,4,91.0,67.0,1965,15.0,82,japan,honda civic
384,32.0,4,91.0,67.0,1965,15.7,82,japan,honda civic (auto)
385,38.0,4,91.0,67.0,1995,16.2,82,japan,datsun 310 gx
390,32.0,4,144.0,96.0,2665,13.9,82,japan,toyota celica gt

**Q3.3 Filter all cars with `cylinders == 4` and `model_year >= 78`.**

In [14]:
# Write your code here
df[(df['cylinders']==4) & (df['model_year']>=78)]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
244,43.1,4,90.0,48.0,1985,21.5,78,europe,volkswagen rabbit custom diesel
245,36.1,4,98.0,66.0,1800,14.4,78,usa,ford fiesta
246,32.8,4,78.0,52.0,1985,19.4,78,japan,mazda glc deluxe
247,39.4,4,85.0,70.0,2070,18.6,78,japan,datsun b210 gx
248,36.1,4,91.0,60.0,1800,16.4,78,japan,honda civic cvcc
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

**Q3.4 Filter all cars where `origin` is **not** `'usa'`, using the `~` (NOT) operator.**

In [15]:
# Write your code here
df[df['origin']!='usa']

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
14,24.0,4,113.0,95.0,2372,15.0,70,japan,toyota corona mark ii
18,27.0,4,97.0,88.0,2130,14.5,70,japan,datsun pl510
19,26.0,4,97.0,46.0,1835,20.5,70,europe,volkswagen 1131 deluxe sedan
20,25.0,4,110.0,87.0,2672,17.5,70,europe,peugeot 504
21,24.0,4,107.0,90.0,2430,14.5,70,europe,audi 100 ls
...,...,...,...,...,...,...,...,...,...
383,38.0,4,91.0,67.0,1965,15.0,82,japan,honda civic
384,32.0,4,91.0,67.0,1965,15.7,82,japan,honda civic (auto)
385,38.0,4,91.0,67.0,1995,16.2,82,japan,datsun 310 gx
390,32.0,4,144.0,96.0,2665,13.9,82,japan,toyota celica gt
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup

# ↕️ **4. Sorting**

### _`.sort_values('col')` → ascending by default | `ascending=False` → descending | pass a list of columns for multi-level sort_

---

**Q4.1 Sort the dataset by `mpg` in descending order and show the top 5 most fuel-efficient cars (name + mpg).**

In [22]:
# Write your code here
df.sort_values('mpg', ascending=False)[['name', 'mpg']].head(5)

                     name   mpg
322             mazda glc  46.6
329   honda civic 1500 gl  44.6
325  vw rabbit c (diesel)  44.3
394             vw pickup  44.0
326    vw dasher (diesel)  43.4

**Q4.2 Sort the dataset first by `weight` (ascending) and then by `horsepower` (descending).**

In [23]:
# Write your code here
df.sort_values(['weight', 'horsepower'],ascending=[True, False])

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
54,35.0,4,72.0,69.0,1613,18.0,71,japan,datsun 1200
144,31.0,4,76.0,52.0,1649,16.5,74,japan,toyota corona
343,39.1,4,79.0,58.0,1755,16.9,81,japan,toyota starlet
345,35.1,4,81.0,60.0,1760,16.1,81,japan,honda civic 1300
53,31.0,4,71.0,65.0,1773,19.0,71,japan,toyota corolla 1200
...,...,...,...,...,...,...,...,...,...
95,12.0,8,455.0,225.0,4951,11.0,73,usa,buick electra 225 custom
90,12.0,8,429.0,198.0,4952,11.5,73,usa,mercury marquis brougham
42,12.0,8,383.0,180.0,4955,11.5,71,usa,dodge monaco (sw)
103,11.0,8,400.0,150.0,4997,14.0,73,usa,chevrolet impala
44,13.0,8,400.0,175.0,5140,12.0,71,usa,pontiac safari (sw)

**Q4.3 Sort the dataset alphabetically by `name` (A to Z) and display the first 5 rows.**

In [24]:
# Write your code here
df.sort_values(['name']).head(5)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
96,13.0,8,360.0,175.0,3821,11.0,73,usa,amc ambassador brougham
9,15.0,8,390.0,190.0,3850,8.5,70,usa,amc ambassador dpl
66,17.0,8,304.0,150.0,3672,11.5,72,usa,amc ambassador sst
315,24.3,4,151.0,90.0,3003,20.1,80,usa,amc concord
257,19.4,6,232.0,90.0,3210,17.2,78,usa,amc concord

# 🧹 **5. Handling Missing Values**

### _`.isnull().sum()` → count missing values per column | `.fillna(value)` → fill missing | `.dropna()` → drop rows/cols with missing values_

---

**Q5.1 Check how many missing values exist in each column of `df`.**

In [28]:
# Write your code here
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

**Q5.2 Fill any missing values in the `horsepower` column with the column's mean value.**

In [31]:
# Write your code here
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mean())

**Q5.3 Find the total number of missing values in the entire dataset (a single number) using `.isnull().sum().sum()`.**

In [30]:
# Write your code here
df.isnull().sum().sum()

np.int64(0)

# 🛠️ **6. Adding, Transforming & Dropping Columns**

### _Create a column by assignment: `df['new'] = ...` | `.apply(func)` → apply a function/lambda element-wise | `.drop(columns=[...])` → remove columns_

---

**Q6.1 Add a new column `weight_kg` by converting `weight` (in lbs) to kilograms (1 lb = 0.4536 kg).**

In [33]:
# Write your code here
df['weight_kg'] = df['weight'] * 0.4536
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,weight_kg
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu,1589.4144
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320,1675.1448
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite,1558.5696
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst,1557.2088
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino,1564.4664
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl,1265.5440
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup,966.1680
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage,1041.0120
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger,1190.7000
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10,1233.7920

**Q6.2 Add a new column `efficiency` using `.apply()` with a lambda: label a car `'Good'` if `mpg >= 25`, `'Average'` if `15 <= mpg < 25`, else `'Poor'`.**

In [ ]:
# Write your code here

**Q6.3 Drop the `name` column and store the result in a new DataFrame called `df_numeric`.**

In [39]:
# Write your code here
df_numeric = df.drop(columns=['name'])
df_numeric

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,weight_kg,hp_per_weight
0,18.0,8,307.0,130.0,3504,12.0,70,usa,1589.4144,0.037100
1,15.0,8,350.0,165.0,3693,11.5,70,usa,1675.1448,0.044679
2,18.0,8,318.0,150.0,3436,11.0,70,usa,1558.5696,0.043655
3,16.0,8,304.0,150.0,3433,12.0,70,usa,1557.2088,0.043694
4,17.0,8,302.0,140.0,3449,10.5,70,usa,1564.4664,0.040591
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,1265.5440,0.030824
394,44.0,4,97.0,52.0,2130,24.6,82,europe,966.1680,0.024413
395,32.0,4,135.0,84.0,2295,11.6,82,usa,1041.0120,0.036601
396,28.0,4,120.0,79.0,2625,18.6,82,usa,1190.7000,0.030095
397,31.0,4,119.0,82.0,2720,19.4,82,usa,1233.7920,0.030147

**Q6.4 Add a new column `hp_per_weight` by dividing `horsepower` by `weight` for every row.**

In [40]:
# Write your code here
df['hp_per_weight'] = df['horsepower'] / df['weight']
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,weight_kg,hp_per_weight
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu,1589.4144,0.037100
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320,1675.1448,0.044679
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite,1558.5696,0.043655
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst,1557.2088,0.043694
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino,1564.4664,0.040591
...,...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl,1265.5440,0.030824
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup,966.1680,0.024413
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage,1041.0120,0.036601
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger,1190.7000,0.030095
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10,1233.7920,0.030147

# 📊 **7. GroupBy & Aggregation**

### _`.groupby('col')` → split by group | `.mean()`, `.max()`, `.count()` → aggregate | `.agg({...})` → different aggregation per column_

---

**Q7.1 Group by `origin` and find the average `mpg` for each origin.**

In [41]:
# Write your code here
df.groupby('origin')['mpg'].mean()

origin
europe    27.891429
japan     30.450633
usa       20.083534
Name: mpg, dtype: float64

**Q7.2 Group by `cylinders` and find the average `mpg` and the maximum `horsepower` for each group using `.agg()`.**

In [48]:
# Write your code here
df.groupby('cylinders').agg({'mpg':'mean','horsepower':'max'})

                 mpg  horsepower
cylinders
3          20.550000       110.0
4          29.286765       115.0
5          27.366667       103.0
6          19.985714       165.0
8          14.963107       230.0

**Q7.3 Group by `model_year` and count how many cars were made each year.**

In [50]:
# Write your code here
df.groupby('model_year').size()

model_year
70    29
71    28
72    28
73    40
74    27
75    30
76    34
77    28
78    36
79    29
80    29
81    29
82    31
dtype: int64

**Q7.4 Group by both `origin` and `cylinders` together, and find the average `mpg` for each combination.**

In [44]:
# Write your code here
df.groupby(['origin', 'cylinders'])['mpg'].mean()

origin  cylinders
europe  4            28.411111
        5            27.366667
        6            20.100000
japan   3            20.550000
        4            31.595652
        6            23.883333
usa     4            27.840278
        6            19.663514
        8            14.963107
Name: mpg, dtype: float64

# 🔢 **8. Value Counts & Unique Values**

### _`.value_counts()` → frequency of each unique value | `.unique()` → array of distinct values | `.nunique()` → count of distinct values_

---

**Q8.1 Use `.value_counts()` to see how many cars come from each `origin`.**

In [51]:
# Write your code here
df['origin'].value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

**Q8.2 Find the number of unique values in `cylinders` and print all the unique values in `model_year`.**

In [ ]:
# Write your code here
df['cylinders'].nunique()
df['model_year'].unique()

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82])

**Q8.3 Using `.value_counts()`, find which `model_year` has the highest number of cars.**

In [59]:
# Write your code here
df['model_year'].value_counts().idxmax()

np.int64(73)

# 🔤 **9. String Operations**

### _`.str.split()`, `.str.upper()`, `.str.contains()` etc. work on string (object) columns via the `.str` accessor_

---

**Q9.1 Create a new column `brand` by extracting the first word from the `name` column (e.g. 'chevrolet chevelle malibu' → 'chevrolet') using `.str.split()`.**

In [ ]:
# Write your code here

**Q9.2 Create a new column `name_upper` by converting the `name` column to uppercase using `.str.upper()`.**

In [ ]:
# Write your code here

**Q9.3 Use `.str.contains('ford', case=False)` to filter all cars whose name contains 'ford'.**

In [ ]:
# Write your code here

# 🧾 **10. Duplicates & Renaming**

### _`.duplicated()` → boolean mask of duplicate rows | `.drop_duplicates()` → remove them | `.rename(columns={...})` → rename columns_

---

**Q10.1 Check whether `df` has any duplicate rows using `.duplicated()`, then remove them with `.drop_duplicates()`.**

In [ ]:
# Write your code here

**Q10.2 Rename the `model_year` column to `year` and the `horsepower` column to `hp`.**

In [ ]:
# Write your code here

**Q10.3 Rename every column name to uppercase in one line, using `.rename(columns=...)` with a dictionary comprehension.**

In [ ]:
# Write your code here

# 🔗 **11. Merge & Concat**

### _`pd.merge(df1, df2, on='col')` → join two DataFrames on a common column | `pd.concat([df1, df2])` → stack DataFrames together_

---

**Q11.1 Create a small lookup DataFrame mapping `origin` codes to full names (`'usa' -> 'United States'`, `'japan' -> 'Japan'`, `'europe' -> 'Europe'`) and merge it with `df` on the `origin` column.**

In [ ]:
# Write your code here

**Q11.2 Create two smaller DataFrames — the first 5 rows and the last 5 rows of `df` — and combine them back together using `pd.concat()`.**

In [ ]:
# Write your code here

**Q11.3 From the merged DataFrame in Q11.1, display only the `name`, `origin`, and the new full-name column for the first 5 rows.**

In [ ]:
# Write your code here

# 💾 **12. Exporting Data**

### _`.to_csv('filename.csv', index=False)` → save a DataFrame to a CSV file_

---

**Q12.1 Filter cars with `mpg > 25`, then save the result to a new file called `efficient_cars.csv` (without the index column).**

In [ ]:
# Write your code here

**Q12.2 Filter cars with `cylinders == 8` and save them to a file called `eight_cylinder_cars.csv`.**

In [ ]:
# Write your code here

**Q12.3 Read back the `efficient_cars.csv` file you saved in Q12.1 using `pd.read_csv()`, and confirm it loaded correctly by checking its shape.**

In [ ]:
# Write your code here